### PR TITLE
ci: configure Renovate to not suggest v2 slf4j upgrades

### PR DESCRIPTION
**Pull request by erikgb**

### CODE REVIEW

**Comment by sverrehu** [comment]
Is this really needed? Please see [the reply from Renovate](https://github.com/statnett/k3a-lag-exporter/pull/60#issuecomment-1747506095) after I closed the PR that suggested updating to v2.

**Comment by erikgb** [comment]
> Is this really needed? Please see [the reply from Renovate](https://github.com/statnett/k3a-lag-exporter/pull/60#issuecomment-1747506095) after I closed the PR that suggested updating to v2.

Probably not, but the next us could wonder WHY we are lagging behind on slf4j versions. After 1567 PRs it might be hard to find the one that got closed.

**Comment by sverrehu** [comment]
> Probably not, but the next us could wonder WHY we are lagging behind on slf4j versions. After 1567 PRs it might be hard to find the one that got closed.

The opposite is also possible: We upgrade to v2 in the future, and do not notice that we don't get any updates.

**Comment by erikgb** [comment]
> > Probably not, but the next us could wonder WHY we are lagging behind on slf4j versions. After 1567 PRs it might be hard to find the one that got closed.
> 
> The opposite is also possible: We upgrade to v2 in the future, and do not notice that we don't get any updates.

True. Closing with the rationale above.

**Pull request closed without merging**
